"""New Migration

Revision ID: 440286ca3972
Revises: 89af5c093f51
Create Date: 2023-06-05 10:21:36.357143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '440286ca3972'
down_revision = '89af5c093f51'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'user', ['username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    # ### end Alembic commands ###
