"""New Migration

Revision ID: 92003aae165a
Revises: 440286ca3972
Create Date: 2023-06-05 12:36:52.807804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92003aae165a'
down_revision = '440286ca3972'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
